name: clean_arch_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  equatable: ^2.0.5
  floor: ^1.4.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  get_it: ^7.6.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  floor_generator: ^1.4.2

flutter:
  uses-material-design: true

  fonts:
    - family: Baskerville
      fonts:
        - asset: asset/fonts/Baskerville.ttc